# -*- coding: utf-8 -*-
"""Lesson 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yriqy7SwsTrjqEHe5MzOvfOm2M15eyv8

Pytorch Workflow
"""

import torch
from torch import nn # nn contains all of Pytorch's building block for neural network
import matplotlib.pyplot as plt

torch.__version__

"""Data preparing and loading


---

Machine learning is game of two parts:
1. Get data into a numerical representation
2. Build a model to learn patterns in that numerical representation

For this , we create known data using linear regression formula.

Using linear regression formula, y=mx+c we make straight line with known parameters.


---

Creating a dataset with linear regression
"""

#creating known parameters
weight =0.7
bias = 0.3

#creating
start = 0
end = 1

step =0.02
X= torch.arange(start,end,step).unsqueeze(dim=1)
y= weight * X +bias
X[:10],y[:10]