# -*- coding: utf-8 -*-
"""Lesson1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IQFyfSwqeLzVH4M8VXgUMsbdhvnRetT-
"""

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


print(torch.__version__)

"""## Introduction to Tensors"""

scalar= torch.tensor(7)

scalar

scalar.ndim

"""only for scalar does item work"""

scalar.item()

vector = torch.tensor([7,6])

vector

"""how many square bracket is the dimension of tensor"""

vector.ndim

vector.shape

vector[1]

#TENSORS
#this is shape
TENSOR = torch.tensor([[[1,2],[4,5],[7,8]]])
#torch.Size([1, 3, 2])
#[[[1,2],[4,5],[7,8]]]<-----this bracket has 1 element
#[[1,2],[4,5],[7,8]]<----- this bracket has 3 elements
#all the elements inside the last bracket has 2 elements

TENSOR

TENSOR.shape

TENSOR.ndim

"""RANDOM TENSORS

"""

random_tensor= torch.rand(1,3,2)
 random_tensor

random_image_size_tensor= torch.rand(size=(3,224,224))
random_image_size_tensor.shape,random_image_size_tensor.ndim

"""Tensors of 0 and 1s"""

zero = torch.zeros(size=(3,4))
zero

ones = torch.ones(3,4)

ones

ones.dtype

"""Creating a range of tensore and tensors like"""

torch.arange(0,10)

range = torch.arange(0,100,10)

range

#tensor like
ten_zeroes = torch.zeros_like(range)

ten_zeroes

"""Tensor data types


Note: Tensor datatypes are one of 3 big issues we run into in pytorch and data science

1.Tensor not right datatype

2.Tensor not right shape

3.Tensor not on the right device
"""

float_tensor = torch.tensor([3,6,9],
                            dtype=None,#data type in tensor
                            device=None,#device tensor is on, diffrent tensor in different device cause issue
                            requires_grad=False)#whether or not to track gradients with this tensors operation

float

float_tensor

float_16_tensor = float_tensor.type(torch.float16)

float_16_tensor

float_16_tensor*float_tensor

